trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  displayName: 'Create ZIP package'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/website.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'Azure for Students(9cbd3592-c2b5-4ba3-b3e1-475bfa93e194)'
    appType: 'webAppLinux'
    appName: 'webb17'
    package: '$(Build.ArtifactStagingDirectory)/website.zip'